### ISSUE TITLE
Graph Indikator won't disapear [Mobile]

### ISSUE THREAD

**Issue by SteveLinkNoah** [DevLeoko/liberty-invoice#1]
Repoduce:
1. Have a open Invoice
2. Go to the Dashboard
3. Open the Invoice on the Dashboard

![Screenshot_20240330_122052_Chrome.jpg](https://github.com/DevLeoko/liberty-invoice/assets/118104058/babe04a5-9f57-4071-b73d-4ca89f1a1467)

![Screenshot_20240330_122114_Chrome.jpg](https://github.com/DevLeoko/liberty-invoice/assets/118104058/bd2b35ae-7e6b-49df-bc17-10b7fa7addee)

**Comment by DevLeoko** [comment]
Thanks for the bug report. The zIndex of the side-modal was not high enough. It should be fixed now
